apache/camel-k-examples

- 11-knative-source-slack/readme.didact.md
- 11-knative-source-slack/readme.md
- 11-knative-source-slack/slack-channel.yaml
- 11-knative-source-slack/slack-consumer.groovy
- 11-knative-source-slack/slack-source.yaml
- 11-knative-source-slack/slack.properties
https://issues.redhat.com/browse/ENTESB-14045
I've used example number 11 (counted the list of selected examples from top to bottom). Let me know if that should be changed.
> Slack Service: Event source design & implementation

- 10-knative-source-salesforce/SalesforceConsumer.java
- 10-knative-source-salesforce/readme.didact.md
- 10-knative-source-salesforce/readme.md
- 10-knative-source-salesforce/salesforce-channel.yaml
- 10-knative-source-salesforce/salesforce-source.yaml
- 10-knative-source-salesforce/salesforce.properties
- README.md
Note: This example requires Apache Camel 3.4.0 or newer due to a bug in camel-salesforce - https://issues.apache.org/jira/browse/CAMEL-15063
> Add knative source example for Salesforce

- 02-serverless-api/API.java
after changes. example 02 works
> replace dependency=camel-quarkus-openapi-java

- kamelets/README.md
- kamelets/aws-s3-to-log/README.md
- kamelets/aws-s3-to-log/flow-binding.yaml
- kamelets/aws-s3-to-log/log-sink.kamelet.yaml
> Added Kamelets folder and first example AWS S3 to Log

- 02-serverless-api/readme.didact.md
- 02-serverless-api/test/yaks-config.yaml
@squakez Can you review it please?
nota: I do not have an environment locally to test that this example is working. I was expecting to have tests played on the PR but seems it is not.
> CAMEL-16765 - use property file: instead of deprecated property-file

- kamelets/aws-s3-to-kafka-with-timestamp-router/README.md
- kamelets/aws-s3-to-log-with-secret/README.md
- kamelets/aws-s3-to-log/README.md
- kamelets/kafka-to-kafka-with-manual-commit/README.md
- kamelets/kafka-to-kafka-with-regex-router/README.md
- kamelets/kafka-to-kafka-with-timestamp-router/README.md
- kamelets/kafka-to-log-with-value-to-key/README.md
- kamelets/kafka-to-s3-streaming-upload/README.md
- kamelets/kafka-to-sqlserver/README.md
- kamelets/postgresql-to-log/README.md
Reformatted kamelets examples with markup for better readability.
> Streamline kamelet README's

- generic-examples/amqp/AmqpConnectionBeanProducer.java
- generic-examples/amqp/README.md
- generic-examples/amqp/amqp.groovy
- generic-examples/amqp/artemis/README.md
@delawen @squakez @oscerd @astefanutti I fixed a few errors and provided some contexts for the examples. The examples appear to run fine. Please kindly review.
> fix and improve amqp example

- generic-examples/caffeine/README.md
- generic-examples/caffeine/camel-caffeine.groovy
@Delawen @tadayosi Fixed some errors in `camel-caffeine.groovy` and provided some context for the examples. Example runs fine. What are your thoughts?
> fix errors and improve caffeine example

- generic-examples/cron/README.md
@delawen Cron example runs successfully.
> add cron example

- generic-examples/databases/PostgresDBAutoDatasource.java
- generic-examples/databases/README.md
- generic-examples/databases/datasource.properties
- generic-examples/databases/postgres-deploy/README.md
- generic-examples/databases/postgres-deploy/postgres-deployment.yaml
@tadayosi @Delawen I fixed some errors in the code and provided more context for the example. The example now runs fine. What do you think?
> Improve and fix Database example

- generic-examples/README.md
- generic-examples/jitpack/README.md
@tadayosi @Delawen This example runs fine. I only made minimal changes here, since imo, the README already provided ample information. Wdyt?
> Improve Jitpack example

- generic-examples/http/NettySecureServer.java
- generic-examples/http/NettyServer.java
- generic-examples/http/PlatformHttpServer.java
- generic-examples/http/PlatformHttpsServer.java
- generic-examples/http/README.md
@tadayosi @Delawen I provided more context for the examples. The examples run ok. Let me know if any change is needed.
> Improve HTTP example

- generic-examples/kafka/README.md
- generic-examples/kafka/SampleKafkaConsumer.java
- generic-examples/kafka/application.properties
- generic-examples/kafka/sasl_ssl/README.md
- generic-examples/kafka/sasl_ssl/SaslSSLKafkaConsumer.java
- generic-examples/kafka/sasl_ssl/SaslSSLKafkaProducer.java
- generic-examples/kafka/sasl_ssl/application.properties
@tadayosi @Delawen I fixed a few errors and provided more info and context for the examples. The examples all run fine. Let me know if there's more to be done.
> Improve Kafka example

- generic-examples/languages/README.md
@tadayosi @Delawen I added more information to the readme. The examples run correctly. Let me know if there's more to be done.
> improve readme

- generic-examples/kamelets/README.md
- generic-examples/kamelets/chuck-norris/chuck.xml
- generic-examples/kamelets/chuck-norris/readme.md
- generic-examples/kamelets/error-handler/error-handler.kamelet.yaml
- generic-examples/kamelets/error-handler/incremental-id-source.kamelet.yaml
- generic-examples/kamelets/error-handler/log-sink.kamelet.yaml
- generic-examples/kamelets/error-handler/readme.md
- generic-examples/kamelets/kameletbindings/README.md
- generic-examples/kamelets/kameletbindings/kb-env-vars.yaml
- generic-examples/kamelets/timer-source-log-sink/log-sink.kamelet.yaml
- generic-examples/kamelets/timer-source-log-sink/readme.md
- generic-examples/kamelets/timer-source-log-sink/timer-source.kamelet.yaml
- generic-examples/kamelets/timer-source/readme.md
- generic-examples/kamelets/timer-source/timer-source.kamelet.yaml
@tadayosi @Delawen I fixed a few errors, did some formatting, and added more info and context for the groups of kamelet examples. The examples run ok. Wdyt?
> Kamelets example

- generic-examples/knative/README.md
@tadayosi @Delawen I updated or removed some outdated information. The readme seems well written imo. The telegram example required a change which I made. All the examples run as expected. Wdyt?
> update knative example readme

- generic-examples/saga/Flight.java
- generic-examples/saga/Payment.java
- generic-examples/saga/README.md
- generic-examples/saga/Train.java
from https://github.com/apache/camel-k/pull/3883
> chore: backport saga fix

- generic-examples/openapi/README.md
> fix: correct open-api syntax

- kamelets/aws-s3-to-kafka-with-timestamp-router/flow-binding.yaml
- kamelets/kafka-to-kafka-with-manual-commit/flow-binding.yaml
- kamelets/kafka-to-kafka-with-regex-router/flow-binding.yaml
- kamelets/kafka-to-kafka-with-timestamp-router/flow-binding.yaml
- kamelets/kafka-to-log-with-value-to-key/flow-binding.yaml
- kamelets/kafka-to-s3-streaming-upload/flow-binding.yaml
- kamelets/kafka-to-sqlserver/flow-binding.yaml
see https://github.com/apache/camel-kamelets/commit/e6d903ed1df57f3c987129ce1c7be32345ef0ffc
> Property brokers renamed for Kafka Kamelet

- generic-examples/kamelets/README.md
- generic-examples/kamelets/user-config/application.properties
- generic-examples/kamelets/user-config/config.properties
- generic-examples/kamelets/user-config/kamelets-pipe-embedded-parameters-2.yaml
- generic-examples/kamelets/user-config/kamelets-pipe-embedded-parameters.yaml
- generic-examples/kamelets/user-config/kamelets-pipe-secret-parameters-2.yaml
- generic-examples/kamelets/user-config/kamelets-pipe-secret-parameters-3.yaml
- generic-examples/kamelets/user-config/kamelets-pipe-secret-parameters.yaml
- generic-examples/kamelets/user-config/kamelets-route-embedded-parameters-2.yaml
- generic-examples/kamelets/user-config/kamelets-route-embedded-parameters.yaml
- generic-examples/kamelets/user-config/kamelets-route-secret-parameters-2.yaml
- generic-examples/kamelets/user-config/kamelets-route-secret-parameters.yaml
- generic-examples/kamelets/user-config/log-sink.properties
- generic-examples/kamelets/user-config/readme.md
- generic-examples/kamelets/user-config/timer-source.properties
- generic-examples/user-config/README.md
* Update existing user configuration examples
* Add kamelets configuration examples
> feat(config): User configuration examples

- generic-examples/http/NettySecureServer.java
- generic-examples/http/NettyServer.java
- generic-examples/http/PlatformHttpServer.java
- generic-examples/http/PlatformHttpsServer.java
- generic-examples/http/README.md
* --resource file:xxx has been removed
* some example `-t service.type=NodePort` to work as expected.
> fix(resource): Remove reference to resource file

- generic-examples/http/PlatformHttpsServer.java
- generic-examples/traits/health/README.md
Follow up from : https://github.com/apache/camel-k/pull/5530
> fix: Deprecated SSL quarkus configuration
